version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "honzito1"
    reviewers:
      - "honzito1"
    labels:
      - "dependabot-test"
      - "ahoj"
    # milestone: 1
    # commit-message:
    #   prefix: "chore"
    target-branch: "main"
    versioning-strategy: "increase"
    rebase-strategy: "auto"
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "honzito1"
    reviewers:
      - "honzito1"
    labels:
      - "dependabot-test"
      - "ahoj"
    # milestone: 1
    # commit-message:
    #   prefix: "chore"
    target-branch: "main"
    rebase-strategy: "auto"
    open-pull-requests-limit: 10
